### ISSUE TITLE
json_value vs json_literal

### ISSUE THREAD

**Issue by zmackie** [ericseppanen/json-parser-toy#1]
this function has two different names in the post. figured it out, but I was confused for a bit...

**Comment by ericseppanen** [comment]
Thanks for letting me know about this.

The naming confusion happened because I was writing the post while writing the code; in the early versions of the code I wrote a function called `json_literal` that only handled literals. As the code developed I expanded that function to handle json arrays and objects also, so I renamed it to `json_value`.

I'll try to figure out a way to clarify this in the text...

**Comment by ericseppanen** [comment]
I added some text to clarify this, and a copy of the `json_value` function. Hope this helps!
